myblog/views/auth.py
# -*- coding: utf-8 -*-
# @Author:              AlanWang
# @Date:                2019-07-10 14:32:59
# @Last Modified by:    AlanWang
# @Last Modified time:  2019-07-31 11:45:25
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from myblog.models import Admin
from myblog.forms import LoginForm
from myblog.utils import redirect_back

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash('Welcome back.', 'info')
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
def logout():
    pass

myblog/views/blog.py
# -*- coding: utf-8 -*-
# @Author:              AlanWang
# @Date:                2019-07-10 14:33:08
# @Last Modified by:    AlanWang
# @Last Modified time:  2019-07-30 14:25:36
from flask import request, Blueprint, render_template, current_app, flash, redirect, url_for, make_response
from flask_login import current_user
from myblog.extensions import db
from myblog.models import Category, Post, Comment
from myblog.forms import AdminCommentForm, CommentForm
from myblog.emails import send_new_comment_email, send_new_reply_email
from myblog.utils import redirect_back

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/', defaults={'page': 1})
@blog_bp.route('/page/<int:page>')
def index(page):
    per_page = current_app.config['MYBLOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page, error_out=True)
    posts = pagination.items
    return render_template('blog/index.html', posts=posts, pagination=pagination)


@blog_bp.route('/about')
def about():
    return render_template('about.html')


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    per_page = current_app.config['MYBLOG_POST_PER_PAGE']
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, posts=posts, pagination=pagination)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    per_page = current_app.config['MYBLOG_POST_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    form = None
    if current_user.is_authenticated: # current user is logined
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['MYBLOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else: # not logined
        form = CommentForm()
        from_admin = False
        reviewed = True

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(author=author, email=email, site=site, body=body,from_admin=from_admin, post=post, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            # send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:
            flash('Comment published', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            # send_new_comment_email(post)
        return redirect(url_for('.show_post', post_id=post.id))

    return render_template('blog/post.html', post=post, comments=comments, form=form, pagination=pagination)


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['MYBLOG_THEMES'].keys():
        abort(404)
    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=30*24*60*60)
    return response

myblog/templates/_sidebar.html
{% if categories %}
<div class="card mb-3">
    <div class="card-header">Categories</div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ url_for('blog.show_category', category_id=category.id) }}">{{ category.name }}</a>
            <span class="badge badge-primary badge-pill">{{ category.posts|length }}</span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Change Theme</button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for theme_name, display_name in config.MYBLOG_THEMES.items() %}
            <a class="dropdown-item" href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">
                {{ display_name }}
            </a>
        {% endfor %}
    </div>
</div>

myblog/templates/about.html
{% extends 'base.html' %}

myblog/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} - MyBlog</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    {{ bootstrap.load_css() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'perfect_blue')) }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="position: fixed;left: 0;top: 0;width: 100%;z-index: 11;">
    <div class="container">
        <a class="navbar-brand" href="/">MyBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                {{ render_nav_item('blog.index', 'Home') }}
                {{ render_nav_item('blog.about', 'About') }}
            </ul>
        </div>
    </div>
</nav>
{% endblock nav %}

<main class="container" style="padding-top: 100px;">
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
    {% endfor %}
    {% block content %}{% endblock content %}
    {% block footer %}
        <footer>
            <p class="float-left">
                <small> &copy; 2019
                    <a href="https://github.com/gloomyline/bluelog" title="Fork me on GitHub">GitHub</a> -
                    <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
                </small>
            </p>
            <p class="float-right">
                <small>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                    {% endif %}
                </small>
            </p>
        </footer>
    {% endblock footer %}
</main>

<small>
    {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
    {% else %}
        <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
    {% endif %}
</small>

{% block scripts %}
{{ bootstrap.load_js() }}
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{{ moment.locale('zh-cn') }}
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}
</body>
</html>

myblog/templates/macros.html
{% macro nav_link(endpoint, text) -%}
<li class="nav-item" {% if request.endpoint and reqeust.endpoint == endpoint %}class="active"{% endif %}>
    <a href="{{ url_for(endpoint, **kwargs) }}">{{ text }}</a>
</li>
{%- endmacro %}

{% macro pager(pagination, fragment='') %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
            <a href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#' }}" class="page-link"><span aria-hidden="true">&larr;</span> Newer</a>
        </li>
        <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
            <a href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#' }}" class="page-link"><span aria-hidden="true">&rarr;</span></a>
        </li>
    </ul>
</nav>
{% endmacro %}